// <auto-generated />
using FinanceScraper.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinanceScraper.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("FinanceScraper.Models.Stock", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvgVol3m");

                    b.Property<string>("Change");

                    b.Property<string>("Currency");

                    b.Property<string>("Date");

                    b.Property<string>("LastPrice");

                    b.Property<string>("MarketCap");

                    b.Property<string>("MarketTime");

                    b.Property<string>("PercentChange");

                    b.Property<string>("Shares");

                    b.Property<string>("Symbol");

                    b.Property<string>("Volume");

                    b.HasKey("ID");

                    b.ToTable("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
